### ISSUE TITLE
Is it included desktop model?

### ISSUE THREAD

**Issue by rootmelo92118** [bhaiest/deckifier#1]

**Comment by TGRush** [comment]
The "Desktop Mode" of the deck is simply a KDE Plasma session with a different Color Scheme

You can install KDE Plasma seperately.

**Comment by newtoblender** [comment]
Stupid question but does this include the virtual keyboard/on screen keyboard from the steam deck?
Not the current awful from that's available in big picture mode.
So you can navigate and type things when in desktop.

I've been waiting for something like this.

**Comment by newtoblender** [comment]
Stupid question but how do to use the virtual keyboard/on screen keyboard from the steam deck to navigate and type things when in desktop.
